// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rentlyo.Infrastructure.Persistence;

#nullable disable

namespace Rentlyo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260910134608_AddVehicles")]
    partial class AddVehicles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rentlyo.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("Rentlyo.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            Code = "vehicles.read",
                            Name = "Read vehicles"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222202"),
                            Code = "vehicles.write",
                            Name = "Write vehicles"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222203"),
                            Code = "reservations.read",
                            Name = "Read reservations"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222204"),
                            Code = "reservations.write",
                            Name = "Write reservations"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222205"),
                            Code = "customers.read",
                            Name = "Read customers"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222206"),
                            Code = "customers.write",
                            Name = "Write customers"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222207"),
                            Code = "settings.manage",
                            Name = "Manage settings"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222208"),
                            Code = "employees.manage",
                            Name = "Manage employees"
                        });
                });

            modelBuilder.Entity("Rentlyo.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Rentlyo.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            Name = "Owner"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            Name = "Manager"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            Name = "Employee"
                        });
                });

            modelBuilder.Entity("Rentlyo.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-222222222201")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111102"),
                            PermissionId = new Guid("22222222-2222-2222-2222-222222222201")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-222222222202")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111102"),
                            PermissionId = new Guid("22222222-2222-2222-2222-222222222202")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-222222222203")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111102"),
                            PermissionId = new Guid("22222222-2222-2222-2222-222222222203")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-222222222204")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111102"),
                            PermissionId = new Guid("22222222-2222-2222-2222-222222222204")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-222222222205")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111102"),
                            PermissionId = new Guid("22222222-2222-2222-2222-222222222205")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-222222222206")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111102"),
                            PermissionId = new Guid("22222222-2222-2222-2222-222222222206")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-222222222207")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111102"),
                            PermissionId = new Guid("22222222-2222-2222-2222-222222222207")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-222222222208")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111102"),
                            PermissionId = new Guid("22222222-2222-2222-2222-222222222208")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111103"),
                            PermissionId = new Guid("22222222-2222-2222-2222-222222222201")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111103"),
                            PermissionId = new Guid("22222222-2222-2222-2222-222222222202")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111103"),
                            PermissionId = new Guid("22222222-2222-2222-2222-222222222203")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111103"),
                            PermissionId = new Guid("22222222-2222-2222-2222-222222222204")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111103"),
                            PermissionId = new Guid("22222222-2222-2222-2222-222222222205")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111103"),
                            PermissionId = new Guid("22222222-2222-2222-2222-222222222206")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111104"),
                            PermissionId = new Guid("22222222-2222-2222-2222-222222222201")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111104"),
                            PermissionId = new Guid("22222222-2222-2222-2222-222222222203")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111104"),
                            PermissionId = new Guid("22222222-2222-2222-2222-222222222204")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111104"),
                            PermissionId = new Guid("22222222-2222-2222-2222-222222222205")
                        });
                });

            modelBuilder.Entity("Rentlyo.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("int");

                    b.Property<int>("MaxVehicles")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SubscriptionPlans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333301"),
                            Code = "free",
                            IsActive = true,
                            MaxUsers = 2,
                            MaxVehicles = 5,
                            Name = "Free"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333302"),
                            Code = "starter",
                            IsActive = true,
                            MaxUsers = 10,
                            MaxVehicles = 25,
                            Name = "Starter"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333303"),
                            Code = "pro",
                            IsActive = true,
                            MaxUsers = 50,
                            MaxVehicles = 100,
                            Name = "Pro"
                        });
                });

            modelBuilder.Entity("Rentlyo.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("Rentlyo.Domain.Entities.TenantSettings", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TenantId");

                    b.ToTable("TenantSettings", (string)null);
                });

            modelBuilder.Entity("Rentlyo.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Rentlyo.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DailyPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "PlateNumber")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("Rentlyo.Domain.Entities.VehicleCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("VehicleCategories", (string)null);
                });

            modelBuilder.Entity("Rentlyo.Domain.Entities.VehicleImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleImages", (string)null);
                });

            modelBuilder.Entity("Rentlyo.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("Rentlyo.Domain.Entities.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rentlyo.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Rentlyo.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rentlyo.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Rentlyo.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rentlyo.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Rentlyo.Domain.Entities.Tenant", b =>
                {
                    b.HasOne("Rentlyo.Domain.Entities.SubscriptionPlan", "Plan")
                        .WithMany("Tenants")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Rentlyo.Domain.Entities.TenantSettings", b =>
                {
                    b.HasOne("Rentlyo.Domain.Entities.Tenant", "Tenant")
                        .WithOne("Settings")
                        .HasForeignKey("Rentlyo.Domain.Entities.TenantSettings", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Rentlyo.Domain.Entities.User", b =>
                {
                    b.HasOne("Rentlyo.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rentlyo.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Rentlyo.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("Rentlyo.Domain.Entities.VehicleCategory", "Category")
                        .WithMany("Vehicles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Rentlyo.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Rentlyo.Domain.Entities.VehicleCategory", b =>
                {
                    b.HasOne("Rentlyo.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Rentlyo.Domain.Entities.VehicleImage", b =>
                {
                    b.HasOne("Rentlyo.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Images")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Rentlyo.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Rentlyo.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Rentlyo.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("Rentlyo.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Settings")
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Rentlyo.Domain.Entities.User", b =>
                {
                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Rentlyo.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Rentlyo.Domain.Entities.VehicleCategory", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
